name: CI test
run-name: build test on branch ${{github.repository}}

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master   
      
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
           node-version: 24

      - name: Debug version
        run: |
            node -v
            npm -v
            
      - name: Install dependecies
        run: npm ci
      
      - name: lint test
        run: npm run lint

      # - name: secret check
      #   run: |
      #     if [ -z "${{secrets.TEST_SECRET}}" ] || [ -z "${{secrets.DOUBL}}" ] ; then
      #         echo "error::secret not found"
      #         exit 1
      #     else
      #         echo "secret found"
      #     fi
      #   env: 
      #     TEST_SECRET: ${{secrets.TEST_SECRET}}
      #     DOUBL: ${{secrets.DOUBL}}
      #     TRIPPLE: ${{secrets.TRIPPLE}}

      # - name: Run secret test
      #   run : | 
      #       echo "secret found"
      #   env: 
      #     TEST_SECRET: ${{secrets.TEST_SECRET}}

      - name: Build applicatioon
        run: npm run build
    
